version: "3.9"

services:
  catalogdb:
    image: postgres:16-alpine
    container_name: catalogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20100
      POSTGRES_DB: catalogdb
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  # catalog.api:
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/Catalog.API/Dockerfile
  #   depends_on:
  #     - catalogdb

volumes:
  postgres_catalog:
